// ============================================================
// Sunspot — Experiences catalog
// Activities, watersports, rentals, tours. Complements the sunbed
// catalog as upsell + cross-sell. Same booking model: 8% service fee.
// ============================================================
(function () {
 'use strict';

 const CATEGORIES = {
 'boat-tour':       { label: 'Boat tour',         icon: '', color: '#0288d1' },
 'private-charter': { label: 'Private charter',   icon: '', color: '#01579b' },
 'rib':             { label: 'RIB / speedboat',   icon: '', color: '#ef6c00' },
 'jetski':          { label: 'Jetski',            icon: '', color: '#c62828' },
 'kayak':           { label: 'Kayak / SUP',       icon: '', color: '#00838f' },
 'diving':          { label: 'Diving',            icon: '', color: '#1565c0' },
 'snorkel':         { label: 'Snorkel tour',      icon: '', color: '#26a69a' },
 'sunset':          { label: 'Sunset cruise',     icon: '', color: '#ff9800' },
 'party':           { label: 'Party boat',        icon: '', color: '#7b1fa2' },
 'parasail':        { label: 'Parasailing',       icon: '', color: '#558b2f' },
 'wakeboard':       { label: 'Wakeboard',         icon: '', color: '#0277bd' },
 'waterski':        { label: 'Waterski',          icon: '', color: '#039be5' },
 'windsurf':        { label: 'Windsurf',          icon: '', color: '#00acc1' },
 'kitesurf':        { label: 'Kitesurf',          icon: '', color: '#26c6da' },
 'flyboard':        { label: 'Flyboard',          icon: '', color: '#e91e63' },
 'tube':            { label: 'Inflatable rides',  icon: '', color: '#fb8c00' },
 'fishing':         { label: 'Fishing',           icon: '', color: '#5d4037' },
 'yoga':            { label: 'Beach + SUP yoga',  icon: '', color: '#9c27b0' },
 'cliff':           { label: 'Cliff jumping',     icon: '', color: '#bf360c' },
 'picnic':          { label: 'Beach picnic',      icon: '', color: '#827717' },
 'culture':         { label: 'Culture tour',      icon: '', color: '#6a1b9a' },
 'transfer':        { label: 'Transfer',          icon: '', color: '#455a64' },
 };

 // Each experience: id, name, cat, departs_from (slug or hub), region,
 // duration_h, price, max_pax, summary, photo, vibe[], operator
 const EXP = [

 // ===== COMINO / BLUE LAGOON =====
 { id: 'comino-rib-sliema', name: 'Sea Adventure Comino RIB', cat: 'rib',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 4, price: 65, max_pax: 12,
 summary: 'High-speed RIB to Blue & Crystal Lagoons + sea caves. Beat the slow ferries — first there, last to leave.',
 vibe: ['adventurer','small-group','snorkel'],
 operator: 'Sea Adventure Malta',
 photo: 'https://picsum.photos/seed/comino-rib/1200/800' },

 { id: 'comino-day-cruise', name: 'Comino Full-Day Catamaran', cat: 'boat-tour',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 8, price: 55, max_pax: 60,
 summary: 'Classic 8-hour catamaran: Blue Lagoon, Crystal Lagoon, Santa Marija. Lunch included.',
 vibe: ['family','classic','lunch'],
 operator: 'Captain Morgan Cruises',
 photo: 'https://picsum.photos/seed/comino-cat/1200/800' },

 { id: 'comino-sunset-rib', name: 'Comino Sunset RIB', cat: 'sunset',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 3, price: 75, max_pax: 12,
 summary: 'Late-afternoon departure, sunset over the cliffs, return in twilight. Includes cocktails.',
 vibe: ['romantic','sunset','small-group'],
 operator: 'Sea Adventure Malta',
 photo: 'https://picsum.photos/seed/comino-sunset/1200/800' },

 // ===== JETSKI =====
 { id: 'jetski-mellieha-30', name: 'Jetski 30-min Mellieha Bay', cat: 'jetski',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieha Bay',
 duration_h: 0.5, price: 60, max_pax: 2,
 summary: 'Solo or tandem jetski in the calm waters of Mellieħa Bay. Instructor on jetski with you for first 5 min.',
 vibe: ['adrenaline','solo','beach'],
 operator: 'Bluewave Watersports',
 photo: 'https://picsum.photos/seed/jetski-mellieha/1200/800' },

 { id: 'jetski-safari-comino', name: 'Jetski Safari to Comino', cat: 'jetski',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieha Bay',
 duration_h: 2.5, price: 180, max_pax: 2,
 summary: '2.5-hour guided jetski safari: Mellieħa → Blue Lagoon → Crystal Lagoon → Santa Marija. Driver license required.',
 vibe: ['adrenaline','adventure','small-group'],
 operator: 'Bluewave Watersports',
 photo: 'https://picsum.photos/seed/jetski-safari/1200/800' },

 // ===== KAYAK / SUP =====
 { id: 'kayak-comino', name: 'Comino Sea Caves Kayak', cat: 'kayak',
 departs_from: 'mellieha', region: 'comino', hub: 'Santa Marija Bay',
 duration_h: 3, price: 45, max_pax: 8,
 summary: 'Guided kayak around Comino — Santa Marija Bay, blue caves, hidden coves no boat fits in.',
 vibe: ['snorkel','quiet','adventurer'],
 operator: 'Sea Kayak Malta',
 photo: 'https://picsum.photos/seed/kayak-comino/1200/800' },

 { id: 'sup-sliema', name: 'SUP Rental — Sliema Front', cat: 'kayak',
 departs_from: 'sliema', region: 'central', hub: 'Tower Road, Sliema',
 duration_h: 1, price: 18, max_pax: 1,
 summary: 'Stand-up paddleboard rental by the hour. Calm bay, beginner-friendly.',
 vibe: ['beginner','solo','quiet'],
 operator: 'Sliema Watersports',
 photo: 'https://picsum.photos/seed/sup-sliema/1200/800' },

 { id: 'sup-tour-gozo', name: 'Gozo Coast SUP Tour', cat: 'kayak',
 departs_from: 'gozo-port', region: 'gozo', hub: 'Marsalforn Bay',
 duration_h: 2.5, price: 55, max_pax: 6,
 summary: 'Paddle Gozo\'s north coast — Marsalforn salt pans, mushroom rock, Wied il-Għasri cliffs.',
 vibe: ['scenic','small-group','photo-worthy'],
 operator: 'Gozo Adventures',
 photo: 'https://picsum.photos/seed/sup-gozo/1200/800' },

 // ===== DIVING / SNORKEL =====
 { id: 'dive-um-el-faroud', name: 'Wreck Dive — Um El Faroud', cat: 'diving',
 departs_from: 'qawra', region: 'south', hub: 'Wied iż-Żurrieq',
 duration_h: 4, price: 90, max_pax: 6,
 summary: 'Open-water dive on Malta\'s most famous wreck (110m tanker). PADI Advanced cert required.',
 vibe: ['advanced','wreck','photo-worthy'],
 operator: 'Dive Systems Malta',
 photo: 'https://picsum.photos/seed/dive-wreck/1200/800' },

 { id: 'snorkel-st-peters', name: 'St Peter\'s Pool Snorkel Tour', cat: 'snorkel',
 departs_from: 'valletta', region: 'south', hub: 'Marsaxlokk',
 duration_h: 3, price: 35, max_pax: 10,
 summary: 'Boat from Marsaxlokk to St Peter\'s Pool with guided snorkel stops. Includes mask + fins.',
 vibe: ['family','snorkel','small-group'],
 operator: 'Maltese Sea Tours',
 photo: 'https://picsum.photos/seed/snorkel-peter/1200/800' },

 // ===== BOAT RENTALS =====
 { id: 'rib-rental-self', name: 'Self-drive RIB (no license)', cat: 'rib',
 departs_from: 'sliema', region: 'central', hub: 'Manoel Island',
 duration_h: 4, price: 220, max_pax: 6,
 summary: 'Half-day self-drive RIB — Sliema, St Paul\'s Bay, swim stops. No license needed if max 30hp.',
 vibe: ['group','adventure','independence'],
 operator: 'Hop on Boat',
 photo: 'https://picsum.photos/seed/rib-rental/1200/800' },

 { id: 'yacht-day-charter', name: 'Yacht Day Charter', cat: 'boat-tour',
 departs_from: 'paceville', region: 'central', hub: 'Portomaso Marina',
 duration_h: 8, price: 880, max_pax: 8,
 summary: 'Private yacht (12m) with skipper — design your own route. Comino, Gozo, Blue Grotto, your call.',
 vibe: ['premium','private','group'],
 operator: 'Portomaso Charters',
 photo: 'https://picsum.photos/seed/yacht-charter/1200/800' },

 // ===== PARTY / SUNSET =====
 { id: 'party-boat-paceville', name: 'Paceville Party Boat', cat: 'party',
 departs_from: 'paceville', region: 'central', hub: 'St George\'s Bay',
 duration_h: 4, price: 50, max_pax: 80,
 summary: 'Friday & Saturday party boat from St George\'s Bay — DJ, open bar (vodka/beer), swim stop at Comino.',
 vibe: ['party','group','sunset'],
 operator: 'Charlie\'s Boat Parties',
 photo: 'https://picsum.photos/seed/party-boat/1200/800' },

 { id: 'sunset-catamaran', name: 'Sunset Catamaran + BBQ', cat: 'sunset',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 3.5, price: 70, max_pax: 40,
 summary: 'Sail from Sliema along the coast, anchor for sunset swim, BBQ dinner on board. 18:00 dep.',
 vibe: ['romantic','dinner','sunset'],
 operator: 'Hera Cruises',
 photo: 'https://picsum.photos/seed/sunset-cat/1200/800' },

 // ===== PARASAIL / FISHING =====
 { id: 'parasail-mellieha', name: 'Parasail Mellieha — Solo or Tandem', cat: 'parasail',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieha Bay',
 duration_h: 0.25, price: 65, max_pax: 2,
 summary: '12-min parasail flight, 150m above the bay. Take-off and landing on the boat — feet stay dry if you want.',
 vibe: ['adrenaline','photo-worthy','quick'],
 operator: 'Bluewave Watersports',
 photo: 'https://picsum.photos/seed/parasail/1200/800' },

 { id: 'fishing-charter', name: 'Half-day Fishing Charter', cat: 'fishing',
 departs_from: 'qawra', region: 'north', hub: 'St Paul\'s Bay',
 duration_h: 4, price: 95, max_pax: 6,
 summary: 'Bottom + trolling fishing trip. Equipment + bait included. Take your catch home (or restaurants nearby will cook it).',
 vibe: ['family','foodie','quiet'],
 operator: 'Reel Malta',
 photo: 'https://picsum.photos/seed/fishing/1200/800' },

 // ===== CULTURE =====
 { id: 'valletta-walk', name: 'Valletta Walking Tour', cat: 'culture',
 departs_from: 'valletta', region: 'central', hub: 'City Gate, Valletta',
 duration_h: 2, price: 18, max_pax: 15,
 summary: '2-hour guided walk through Valletta — St John\'s Cathedral, Upper Barrakka Gardens, hidden gems. English/Italian.',
 vibe: ['culture','beginner','solo'],
 operator: 'Colour My Travel',
 photo: 'https://picsum.photos/seed/valletta-walk/1200/800' },

 { id: 'mdina-night-tour', name: 'Mdina Night Tour', cat: 'culture',
 departs_from: 'valletta', region: 'central', hub: 'Mdina Gate',
 duration_h: 2, price: 22, max_pax: 12,
 summary: 'Atmospheric evening walk through the Silent City — narrow lanes, ghost stories, knights\' palaces.',
 vibe: ['romantic','culture','small-group'],
 operator: 'Heritage Malta Tours',
 photo: 'https://picsum.photos/seed/mdina-night/1200/800' },

 // ===== TRANSFERS =====
 { id: 'airport-transfer-private', name: 'Private Airport Transfer', cat: 'transfer',
 departs_from: 'airport', region: 'south', hub: 'MLA arrivals',
 duration_h: 0.75, price: 35, max_pax: 4,
 summary: 'Door-to-door from airport to any hotel — fixed price, no surge. Meet & greet with name sign.',
 vibe: ['arrival','no-stress','family'],
 operator: 'Sunspot Concierge',
 photo: 'https://picsum.photos/seed/transfer/1200/800' },

 // =========================================================
 // PRIVATE CHARTERS — boats from half-day to full-week
 // =========================================================
 { id: 'sailing-yacht-halfday', name: 'Private Sailing Yacht — Half Day', cat: 'private-charter',
 departs_from: 'msida', region: 'central', hub: 'Msida Marina',
 duration_h: 4, price: 450, max_pax: 8,
 summary: 'Half-day skippered Bavaria 38 — sail down the harbour, swim off the back, lunch on board. Up to 8 guests, all kit included.',
 vibe: ['romantic','group','swim-stop','small-group'],
 operator: 'Sunspot Sailing',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mistra-2560x1440-1.jpeg' },

 { id: 'sailing-yacht-fullday', name: 'Private Sailing Yacht — Full Day', cat: 'private-charter',
 departs_from: 'msida', region: 'central', hub: 'Msida Marina',
 duration_h: 8, price: 780, max_pax: 8,
 summary: 'Full-day skippered sail — Sliema → Comino → Crystal → St Paul\'s with anchored swim stops. Lunch + drinks included.',
 vibe: ['group','swim-stop','full-day','romantic'],
 operator: 'Bezz Yachting',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg',
 spec: { boat: 'Bavaria 38', length_m: 11.5, year: 2019, engine: 'Volvo Penta 40hp', cabins: 3, heads: 2 },
 crew: { skipper: true, steward: false, chef: false },
 itinerary: [
   { time: '09:30', name: 'Boarding at Msida Marina', detail: 'Skipper briefing + safety + first coffee on deck.' },
   { time: '10:00', name: 'Cast off — head north', detail: 'Sail past Sliema and Tigne; if wind allows, hoist sails off St Julian\'s.' },
   { time: '11:30', name: 'Anchor: St Paul\'s Bay', detail: 'First swim, snorkel gear out. Light bites + prosecco served on deck.' },
   { time: '13:00', name: 'Lunch underway', detail: 'Two-course lunch as you sail north to Comino.' },
   { time: '14:30', name: 'Anchor: Comino', detail: 'Long anchor stop at Crystal or Blue Lagoon depending on conditions. Swim, paddleboard.' },
   { time: '17:00', name: 'Return sail', detail: 'Slower run back along the north coast as the wind shifts.' },
   { time: '18:30', name: 'Dock at Msida', detail: 'Drinks while the boat is tied up; usual end time 19:00.' },
 ],
 includes: ['Skipper', 'Fuel', 'Mooring fees', 'Lunch + drinks (incl. wine + beer)', 'Snorkelling gear', '2× paddleboards', 'Wi-Fi hotspot'],
 not_included: ['Tip for the skipper (suggested €30–50/guest)', 'Pickup from your hotel'],
 bring: ['Towel + sun cream', 'Swimwear', 'Light layer for the return sail', 'Cash for the skipper tip'],
 faq: [
   { q: 'What if the wind dies?', a: 'We motor. The engine is rated for 7 knots — Comino and back is always reachable. The boat is a sail-or-motor by design.' },
   { q: 'Can we change the route?', a: 'Yes — the route above is the default. Swap any anchor stop the morning of, subject to wind direction. The skipper is local and knows where the wind sits each day.' },
   { q: 'Are kids welcome?', a: 'Yes, from age 4 with parental signature. Kid-sized lifejackets aboard. Mosquito-spray welcome.' },
 ],
 },

 { id: 'catamaran-private-charter', name: 'Private Catamaran Charter', cat: 'private-charter',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 8, price: 1100, max_pax: 24,
 summary: 'Lagoon 42 cat with crew of three — your guest list, your stops. Catered lunch, music system, two paddleboards on board.',
 vibe: ['celebration','group','catered','full-day'],
 operator: 'Captain Morgan Cruises',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Blue-Lagoon-2560x1440-1.jpeg',
 spec: { boat: 'Lagoon 42', length_m: 12.8, year: 2021, engine: 'Twin 40hp', cabins: 4, heads: 4 },
 crew: { skipper: true, steward: true, chef: true },
 itinerary: [
   { time: '10:00', name: 'Boarding at Sliema Ferries', detail: 'Crew welcome with bubbles + a playlist handover — your Spotify, your day.' },
   { time: '10:30', name: 'Cast off', detail: 'Quick swim stop at St Paul\'s if the group wants to ease in.' },
   { time: '12:00', name: 'Anchor: Comino', detail: 'Long stop at Crystal Lagoon or Blue Lagoon — chef prepares lunch on board while you swim.' },
   { time: '14:00', name: 'Sit-down lunch', detail: 'Maltese mezze, fresh fish, two desserts. Wine and prosecco flowing.' },
   { time: '15:30', name: 'Move boats — Santa Marija', detail: 'Quiet anchorage on Comino\'s north — paddleboards out, music up.' },
   { time: '17:30', name: 'Sunset return', detail: 'Slow cruise back via Mistra and Bahar ic-Caghaq. Sundowner cocktails served.' },
   { time: '19:00', name: 'Dock at Sliema', detail: 'Most groups extend by an hour to keep the deck going — flat fee €150/hr.' },
 ],
 includes: ['Crew of three (skipper, steward, chef)', 'Fuel + mooring', 'Catered lunch (Maltese mezze + main + dessert)', 'Open bar (wine, beer, prosecco, soft drinks)', '2× paddleboards', 'Snorkelling gear', 'Bluetooth sound system', 'Towels'],
 not_included: ['Premium spirits (vodka, gin, rum bar — €120 add-on)', 'Crew tip (suggested €100–200 for the group)', 'Photographer'],
 bring: ['Swimwear + towel', 'Sun cream (reef-safe)', 'Hat + sunglasses', 'Playlist on your phone'],
 faq: [
   { q: 'Can we have a DJ?', a: 'Yes — €350 add-on, includes mixer + monitor + DJ for the day. Pre-book; we use the same five DJs we trust.' },
   { q: 'How many people fit comfortably?', a: 'Licensed for 24. Comfortable for 18. Anything over 20 means people are sharing deck space; under 15 is plenty of room.' },
   { q: 'What if it rains?', a: 'The Lagoon 42 has a covered cockpit + saloon — 16 people fit inside. We sail anyway. If it\'s storm-force (rare), the skipper cancels at 18:00 the night before and you get a full refund.' },
   { q: 'Can we extend?', a: 'Yes — flat €150/hour. Pay aboard. Most extensions are 1-2 hours past the original return time.' },
 ],
 },

 { id: 'speedboat-private-halfday', name: 'Private Speedboat — Half Day', cat: 'private-charter',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 4, price: 350, max_pax: 8,
 summary: 'Skippered speedboat to wherever you want — Comino sea caves, the south coast cliffs, Gozo for lunch. You choose.',
 vibe: ['flexible','small-group','swim-stop'],
 operator: 'Sea Adventure Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg' },

 { id: 'sicily-day-cat', name: 'Sicily Day Trip — Catamaran', cat: 'boat-tour',
 departs_from: 'mgarr-gozo', region: 'gozo', hub: 'Mġarr Harbour',
 duration_h: 12, price: 120, max_pax: 40,
 summary: 'Pozzallo crossing on the fast cat. Wander Modica, eat granita, be back by midnight. Passport required.',
 vibe: ['adventure','full-day','food'],
 operator: 'Virtu Ferries',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mgarr-Ix-xini-2560x1440-1.jpeg' },

 { id: 'fishing-private-fullday', name: 'Private Fishing Charter — Full Day', cat: 'fishing',
 departs_from: 'marsaxlokk', region: 'south', hub: 'Marsaxlokk Harbour',
 duration_h: 8, price: 280, max_pax: 6,
 summary: 'Big-game day on a Sea Hunter 33 — trolling for amberjack, tuna and dorado off the south coast. All gear + ice box for the catch.',
 vibe: ['fishing','adventure','full-day'],
 operator: 'Marsaxlokk Charters',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mistra-2560x1440-1.jpeg' },

 { id: 'sunset-vittoriosa', name: 'Vittoriosa Sunset Aperitif Cruise', cat: 'sunset',
 departs_from: 'vittoriosa', region: 'south', hub: 'Vittoriosa Waterfront',
 duration_h: 2, price: 55, max_pax: 30,
 summary: 'Glass of bubbly as the bastions go gold. Quieter than the Sliema sunset boats and the Three Cities view is hard to beat.',
 vibe: ['sunset','romantic','small-group','aperitif'],
 operator: 'Three Cities Cruises',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Rinella-2560x1440-1.jpeg' },

 { id: 'glass-bottom-comino', name: 'Glass-bottom Boat — Comino Caves', cat: 'boat-tour',
 departs_from: 'cirkewwa', region: 'north', hub: 'Ċirkewwa Pier',
 duration_h: 1.5, price: 30, max_pax: 30,
 summary: 'See the seabed without getting wet. Best for kids and non-swimmers — Crystal Lagoon water clarity is hard to overstate.',
 vibe: ['family','kid-friendly','short'],
 operator: 'Comino Glass Boats',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg' },

 { id: 'booze-cruise-comino', name: 'Comino Day Booze Cruise', cat: 'party',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 7, price: 60, max_pax: 80,
 summary: '11:00 sail to Crystal + Blue Lagoon with open bar, DJ on the upper deck and two long swim stops. Adults only, weekends from June.',
 vibe: ['party','group','open-bar'],
 operator: 'Hera Cruises',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Blue-Lagoon-2560x1440-1.jpeg' },

 // =========================================================
 // SUN ACTIVITIES — yoga, picnics, cliff-jumping, walks
 // =========================================================
 { id: 'beach-yoga-sliema', name: 'Beach Yoga — Sliema Front', cat: 'yoga',
 departs_from: 'sliema', region: 'central', hub: 'Exiles Bay Lido',
 duration_h: 1, price: 25, max_pax: 16,
 summary: '07:00 vinyasa flow on the limestone slabs at Exiles. Bring a towel, the lido provides the mat. Coffee from the kiosk after.',
 vibe: ['wellness','morning','small-group'],
 operator: 'Yogagroup Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Exiles-Bay-2560x1440-1-scaled-1.webp' },

 { id: 'sup-yoga-spinola', name: 'SUP Yoga — Spinola Bay', cat: 'yoga',
 departs_from: 'st-julians', region: 'central', hub: 'Spinola Bay',
 duration_h: 1.25, price: 40, max_pax: 10,
 summary: 'Yoga on a paddleboard, anchored in flat water at Spinola Bay. Falls in are part of the experience. All levels welcome — no experience needed.',
 vibe: ['wellness','playful','small-group'],
 operator: 'Maltaqua Sports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Balluta-2560x1440-1.jpeg' },

 { id: 'sunset-yoga-golden-bay', name: 'Sunset Yoga — Golden Bay', cat: 'yoga',
 departs_from: 'mellieha', region: 'north', hub: 'Golden Bay',
 duration_h: 1.5, price: 30, max_pax: 20,
 summary: 'Slow flow + 10-minute meditation as the sun drops behind Lippija. Sandy spot at the south end of the bay, away from the bar music.',
 vibe: ['wellness','sunset','calm'],
 operator: 'Yogagroup Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Golden-Bay-2560x1440-1.jpeg' },

 { id: 'cliff-jumping-comino', name: 'Cliff Jumping — Comino', cat: 'cliff',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 4, price: 70, max_pax: 12,
 summary: 'RIB to Comino\'s south cliffs. Three jump points from 2m, 5m and 10m, with a qualified jump-guide and rescue swimmer in the water.',
 vibe: ['adventure','adrenalin','small-group'],
 operator: 'Sea Adventure Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg' },

 { id: 'coasteering-dingli', name: 'Coasteering — Dingli Cliffs', cat: 'cliff',
 departs_from: 'dingli', region: 'south', hub: 'Dingli Cliffs car park',
 duration_h: 3, price: 65, max_pax: 10,
 summary: 'Scramble, swim, leap and squeeze along the base of the Dingli Cliffs. Wetsuits, helmets and harnesses provided.',
 vibe: ['adventure','adrenalin','active'],
 operator: 'Malta Wild Adventures',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Ghar-Lapsi-2560x1440-1.jpeg' },

 { id: 'beach-picnic-mistra', name: 'Beach Picnic Package — Mistra Bay', cat: 'picnic',
 departs_from: 'st-pauls-bay', region: 'north', hub: 'Mistra Bay',
 duration_h: 4, price: 80, max_pax: 6,
 summary: 'Sunbed, parasol and a Maltese hamper — pastizzi, ftira, olives, gbejna, wine — delivered to your spot. Quiet rocky cove, mid-week sweet spot.',
 vibe: ['food','quiet','romantic','family'],
 operator: 'Picnic Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mistra-2560x1440-1.jpeg' },

 { id: 'saltpan-walk-marsalforn', name: 'Salt-Pan Walking Tour — Marsalforn', cat: 'culture',
 departs_from: 'marsalforn', region: 'gozo', hub: 'Xwejni car park',
 duration_h: 2, price: 25, max_pax: 14,
 summary: 'Walk the geometric salt pans from Xwejni to Qbajjar with a fifth-generation salt-maker. Take home a small jar of salt and a story.',
 vibe: ['culture','quiet','gozo','walking'],
 operator: 'Leli tal-Melħ',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2021/12/Xwejni-Bay-2560x1440-1.jpeg' },

 { id: 'sunrise-sup-coffee', name: 'Sunrise SUP + Coffee Tour', cat: 'kayak',
 departs_from: 'st-julians', region: 'central', hub: 'Balluta Bay',
 duration_h: 2, price: 38, max_pax: 10,
 summary: '05:30 launch. Paddle from Balluta to Sliema for sunrise, beach coffee from the early kiosk, paddle back. The flattest water of the day.',
 vibe: ['wellness','morning','calm'],
 operator: 'Maltaqua Sports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Balluta-2560x1440-1.jpeg' },

 { id: 'photo-walk-sunset', name: 'Sunset Photography Workshop', cat: 'culture',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Front',
 duration_h: 2.5, price: 120, max_pax: 6,
 summary: 'Three hours with a working travel photographer — composition, light, and how to shoot the Maltese coast without making it look like a postcard. Phone or DSLR.',
 vibe: ['creative','small-group','sunset'],
 operator: 'Frame Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Fond-Ghadir-2560x1440-1.jpeg' },

 // =========================================================
 // MORE PRIVATE CHARTERS — bigger range, more boat options
 // =========================================================
 { id: 'power-yacht-halfday', name: 'Power Yacht — Half Day', cat: 'private-charter',
 departs_from: 'msida', region: 'central', hub: 'Msida Marina',
 duration_h: 4, price: 950, max_pax: 10,
 summary: 'Princess 50 with skipper + steward. AC saloon, swim platform, ice and prosecco aboard. Half-day Sliema → Comino loop.',
 vibe: ['premium','group','catered','small-group'],
 operator: 'Princess Charters Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg' },

 { id: 'power-yacht-fullday', name: 'Power Yacht — Full Day', cat: 'private-charter',
 departs_from: 'msida', region: 'central', hub: 'Msida Marina',
 duration_h: 8, price: 1750, max_pax: 10,
 summary: 'Princess 50 with skipper, steward and chef. Lunch on board, four anchor stops, sunset return — Sliema → Gozo → Comino.',
 vibe: ['premium','group','catered','full-day'],
 operator: 'Princess Charters Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Blue-Lagoon-2560x1440-1.jpeg',
 spec: { boat: 'Princess 50', length_m: 15.5, year: 2022, engine: 'Twin Volvo 500hp', cabins: 3, heads: 3 },
 crew: { skipper: true, steward: true, chef: true },
 itinerary: [
   { time: '09:30', name: 'Boarding at Msida Marina', detail: 'Welcome aboard with espresso + cornetti, route review with the skipper.' },
   { time: '10:00', name: 'Cast off — Comino', detail: '40-min cruise (twin 500hp; the boat does 22 knots cruise). Beat the day-cruisers to the lagoon.' },
   { time: '11:00', name: 'Anchor: Crystal Lagoon', detail: 'First swim, paddleboards out. Chef serves brunch on the foredeck.' },
   { time: '13:00', name: 'Move — Gozo coast', detail: 'Cruise along Gozo\'s south coast to Mġarr ix-Xini or Wied il-Għasri.' },
   { time: '14:30', name: 'Anchor + lunch', detail: 'Three-course lunch on the upper deck. Maltese fish, local wine.' },
   { time: '16:30', name: 'Final swim — Blue Lagoon', detail: 'When the day-cruise boats have left, the lagoon is yours.' },
   { time: '18:00', name: 'Sunset return', detail: 'Cocktails on the way back, music optional. Dock by 19:00.' },
 ],
 includes: ['Crew of three (skipper, steward, chef)', 'Fuel + mooring', 'Catered brunch + lunch + canapés', 'Open premium bar (wine, beer, prosecco, soft drinks)', '2× paddleboards', 'Snorkelling gear', 'Sound system + Apple TV', 'Towels + suncream'],
 not_included: ['Champagne (bring your own with no corkage)', 'Crew tip (suggested €150–250 for the group)'],
 bring: ['Swimwear + towel (provided too)', 'Layer for the return cruise'],
 faq: [
   { q: 'Is the Princess too big for the lagoon?', a: 'No — the Princess 50 anchors in 8m. Crystal is 5–8m at the centre, plenty of room.' },
   { q: 'Can we add a Sicily day trip?', a: 'No — the Princess is licensed for Maltese waters only. For Sicily we put you on the catamaran or the Virtu fast cat.' },
   { q: 'Is sea-sickness a problem?', a: 'Almost never on a Princess this size. Twin engines + flybridge stabilise things. If you\'re prone, take a tablet 30 min before boarding.' },
 ],
 },

 { id: 'cabin-cat-weekend', name: 'Cabin Catamaran — Long Weekend', cat: 'private-charter',
 departs_from: 'msida', region: 'central', hub: 'Msida Marina',
 duration_h: 72, price: 4800, max_pax: 8,
 summary: 'Sleep-aboard Lagoon 42 from Friday to Monday with skipper. Sail Malta → Gozo → Comino, dinners ashore. 4 cabins, 4 heads.',
 vibe: ['multi-day','romantic','group','sleep-aboard'],
 operator: 'Bezz Yachting',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mgarr-Ix-xini-2560x1440-1.jpeg',
 spec: { boat: 'Lagoon 42', length_m: 12.8, year: 2021, engine: 'Twin 40hp', cabins: 4, heads: 4 },
 crew: { skipper: true, steward: false, chef: false },
 itinerary: [
   { time: 'Friday 18:00', name: 'Boarding + sunset sail', detail: 'Check-in at Msida, two-hour shake-down sail past Sliema, anchor at St Paul\'s.' },
   { time: 'Friday 21:00', name: 'Dinner ashore in Mistra', detail: 'Skipper takes the tender in to dinner at Mistra Pier (your booking).' },
   { time: 'Saturday 08:00', name: 'Sail to Gozo', detail: 'Slow sail across the channel — anchor in Mġarr ix-Xini for the day.' },
   { time: 'Saturday 19:00', name: 'Dinner in Mġarr village', detail: 'Tender into Mġarr harbour. Try Tmun for a long fish lunch turned into dinner.' },
   { time: 'Sunday 09:00', name: 'Comino day', detail: 'Cross to Comino. Crystal + Blue Lagoon all day. Anchor overnight in Santa Marija.' },
   { time: 'Sunday 20:00', name: 'BBQ on Cominotto', detail: 'Tender across to Cominotto for a sunset BBQ on the islet. Skipper grills.' },
   { time: 'Monday 09:00', name: 'Slow return to Malta', detail: 'Sail back via Mellieħa and Salina. Dock at Msida by 13:00.' },
 ],
 includes: ['Skipper (sleeps aboard)', 'Fuel + mooring fees for 3 nights', 'Linens + towels', 'Snorkelling gear', '2× paddleboards', 'Tender + outboard for shore trips', 'Sound system + Wi-Fi'],
 not_included: ['Food + drink on board (provisioning service available, €350)', 'Restaurants ashore', 'Skipper tip (suggested €200–400 for the trip)'],
 bring: ['Soft duffel bag (no hard suitcases on board)', 'Swimwear + towel (also provided)', 'Layer for evenings', 'Light shoes for shore trips'],
 faq: [
   { q: 'How private are the cabins?', a: 'Four cabins, four heads. Each cabin sleeps two with a private head + shower. Couples normally take one cabin each; friends-of-couples sometimes split a cabin.' },
   { q: 'Can we skip the marina nights and stay at anchor?', a: 'Yes — the boat\'s set up for it. Solar + battery handle a fridge + lights + fans for 3 days without shore power.' },
   { q: 'Provisioning?', a: 'We offer a €350 hampers-and-fridge service that covers all three days for 8 people. Or we drop you at the Cirkewwa supermarket on Friday morning before the sunset sail.' },
   { q: 'What about Sicily?', a: 'Possible as a 4-day extension (+€1,200). Different boat needed — the Lagoon 42 isn\'t licensed for cross-channel. We swap to a Lagoon 50.' },
 ],
 },

 { id: 'twin-rib-convoy', name: 'Twin RIB Convoy — Group of 24', cat: 'private-charter',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 5, price: 1100, max_pax: 24,
 summary: 'Two skippered RIBs running in formation — 12 per boat. Stops at Crystal, Blue Lagoon and Santa Marija. Faster than any catamaran of the same capacity.',
 vibe: ['group','adventure','speed'],
 operator: 'Sea Adventure Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg' },

 { id: 'bachelor-catamaran', name: 'Bachelor / Bachelorette Catamaran', cat: 'private-charter',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 6, price: 1400, max_pax: 25,
 summary: 'Friday or Saturday Lagoon 42 charter with DJ, paddleboards, open bar and a Comino swim stop. Decorated to brief, photographer add-on available.',
 vibe: ['celebration','party','group','catered'],
 operator: 'Hera Cruises',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Blue-Lagoon-2560x1440-1.jpeg' },

 { id: 'corporate-charter', name: 'Corporate Day Charter', cat: 'private-charter',
 departs_from: 'msida', region: 'central', hub: 'Msida Marina',
 duration_h: 6, price: 2200, max_pax: 30,
 summary: 'Off-site for the team — Sunseeker Manhattan 73 with crew of four. Branded welcome, breakout corners on the upper deck, served lunch.',
 vibe: ['corporate','catered','group'],
 operator: 'Bezz Yachting',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mistra-2560x1440-1.jpeg',
 spec: { boat: 'Sunseeker Manhattan 73', length_m: 22.5, year: 2020, engine: 'Twin MAN 1200hp', cabins: 4, heads: 4 },
 crew: { skipper: true, steward: true, chef: true },
 itinerary: [
   { time: '09:00', name: 'Branded welcome at Msida', detail: 'Your branding on signage at the pontoon. Coffee + cornetti as guests arrive.' },
   { time: '10:00', name: 'Cast off', detail: 'Settle-in lap past Sliema while guests find their corner of the boat.' },
   { time: '11:00', name: 'Anchor: St Paul\'s', detail: 'First swim. Optional team-building session up on the foredeck.' },
   { time: '12:30', name: 'Sit-down lunch', detail: 'Served Mediterranean lunch in the saloon. Wine pairing on the table.' },
   { time: '14:30', name: 'Anchor: Comino', detail: 'Crystal Lagoon afternoon. Watersports rigged; paddleboards + Seabob available.' },
   { time: '16:30', name: 'Return + closing', detail: 'Sundowner cocktails on the way back. Dock by 15:00 or 17:00 depending on the booking.' },
 ],
 includes: ['Crew of four', 'Fuel + mooring', 'Branded signage (logo on pontoon + welcome screen)', 'Served lunch + canapés', 'Open bar (wine, beer, soft drinks)', '2× paddleboards', 'Seabob (1 hour included)', 'Sound system + Wi-Fi + Apple TV'],
 not_included: ['Photographer (+€400)', 'Drone footage (+€350)', 'Champagne service (+€200)', 'Crew tip (suggested €300–500)'],
 bring: ['Guest list 7 days ahead', 'Logo file in vector format (SVG or AI)', 'Dietary requirements ahead of time'],
 faq: [
   { q: 'Can we do a presentation on board?', a: 'Yes — Apple TV in the saloon, mirror from any Mac. Foredeck has a wireless mic + speakers for outdoor talks.' },
   { q: 'Insurance?', a: 'Boat is fully insured for 30 guests. Operator carries €2M public liability. We can issue a certificate to your HR/Legal in advance.' },
   { q: 'Dietary requirements?', a: 'Chef accommodates everything with 5 days\' notice. Allergens flagged on the menu card.' },
   { q: 'Off-season pricing?', a: 'October-April: €1,600 + boat heated. April + October are the best value months — full crew, half the rest of the marina.' },
 ],
 },

 { id: 'live-jazz-sunset', name: 'Live Jazz Sunset Cruise', cat: 'sunset',
 departs_from: 'sliema', region: 'central', hub: 'The Strand',
 duration_h: 2.5, price: 95, max_pax: 40,
 summary: 'A jazz trio on the upper deck, two-cocktail minimum, the harbour at golden hour. Sails Thursdays and Sundays from June.',
 vibe: ['sunset','music','aperitif','date'],
 operator: 'Malta Sunset Boats',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Rinella-2560x1440-1.jpeg' },

 { id: 'sailing-lessons', name: 'Sailing Lessons — RYA Day Skipper', cat: 'private-charter',
 departs_from: 'msida', region: 'central', hub: 'Royal Malta Yacht Club',
 duration_h: 40, price: 1100, max_pax: 4,
 summary: 'Five-day RYA Day Skipper course — theory, practical, night sail, certificate. Run from the RMYC, May to October. Includes course materials.',
 vibe: ['learning','small-group','multi-day'],
 operator: 'RMYC Sailing School',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mistra-2560x1440-1.jpeg' },

 // =========================================================
 // WATERSPORTS — properly broken out, every major activity
 // =========================================================
 { id: 'wakeboard-mellieha', name: 'Wakeboard Session — Mellieħa Bay', cat: 'wakeboard',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay watersports kiosk',
 duration_h: 0.25, price: 35, max_pax: 1,
 summary: '15-minute boat-pull wakeboard run in flat-water Mellieħa Bay. Coach in the boat, board and helmet included. Beginners welcome.',
 vibe: ['adrenalin','solo','short'],
 operator: 'Mellieha Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },

 { id: 'waterski-mellieha', name: 'Water-Ski Session — Mellieħa Bay', cat: 'waterski',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay watersports kiosk',
 duration_h: 0.25, price: 35, max_pax: 1,
 summary: '15 minutes on twin or mono skis. Step-by-step from deep-water start. Mellieħa\'s big sheltered bay is the easiest place in Malta to learn.',
 vibe: ['adrenalin','solo','short'],
 operator: 'Mellieha Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },

 { id: 'windsurf-mellieha', name: 'Windsurf Rental — Mellieħa Bay', cat: 'windsurf',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay (south end)',
 duration_h: 1, price: 28, max_pax: 1,
 summary: 'Hourly rental — board, sail and wetsuit if you want one. Mellieħa\'s afternoon NW wind is reliable, the south end of the bay stays flat enough to start.',
 vibe: ['solo','active','wind'],
 operator: 'Mellieha Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },

 { id: 'windsurf-lesson-mellieha', name: 'Windsurf Lesson — Beginner', cat: 'windsurf',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay (south end)',
 duration_h: 2, price: 70, max_pax: 4,
 summary: 'Two-hour beginner lesson — uphaul, sail-handling, first runs across the bay. Small group, one instructor in the water with you.',
 vibe: ['learning','small-group','wind'],
 operator: 'Mellieha Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },

 { id: 'kitesurf-lesson-mellieha', name: 'Kitesurf Lesson — Beginner', cat: 'kitesurf',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay (south end)',
 duration_h: 3, price: 130, max_pax: 2,
 summary: 'Three-hour intro — kite control on land, body-drag in the water, first standing attempts if the wind plays ball. IKO-certified instructor.',
 vibe: ['learning','adrenalin','wind'],
 operator: 'Kitesurf Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },

 { id: 'flyboard-st-pauls', name: 'Flyboard — St Paul\'s Bay', cat: 'flyboard',
 departs_from: 'st-pauls-bay', region: 'north', hub: 'Bugibba waterfront',
 duration_h: 0.5, price: 95, max_pax: 1,
 summary: '30-minute flyboard with instructor. Includes 10-minute briefing + 20 minutes in the water. By the third minute you\'re standing.',
 vibe: ['adrenalin','solo','show-off'],
 operator: 'Bugibba Flyboard',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Buggiba-Front-2560x1440-1.jpeg' },

 { id: 'banana-mellieha', name: 'Banana Boat Ride — Mellieħa', cat: 'tube',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay watersports kiosk',
 duration_h: 0.25, price: 18, max_pax: 8,
 summary: 'Six-person banana boat pulled around the bay. Loud, wet, undignified — the kids will demand a second run.',
 vibe: ['family','playful','group','short'],
 operator: 'Mellieha Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },

 { id: 'donut-bugibba', name: 'Donut Ride — Bugibba', cat: 'tube',
 departs_from: 'bugibba', region: 'north', hub: 'Bugibba waterfront',
 duration_h: 0.25, price: 15, max_pax: 4,
 summary: 'Inflatable donut pulled at speed. Pick "calm" or "spin" — the operator listens to neither.',
 vibe: ['family','playful','group','short'],
 operator: 'Bugibba Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Buggiba-Front-2560x1440-1.jpeg' },

 { id: 'seabob-rental', name: 'Seabob Underwater Scooter', cat: 'kayak',
 departs_from: 'sliema', region: 'central', hub: 'Tigne Point',
 duration_h: 1, price: 95, max_pax: 1,
 summary: 'An hour with a Seabob F5 — torpedo through the shallows, dive on demand. Onshore briefing, lifeguard supervision in the water.',
 vibe: ['novel','solo','adrenalin'],
 operator: 'Aquaholics Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Fond-Ghadir-2560x1440-1.jpeg' },

 { id: 'scuba-try-dive', name: 'Scuba Try-Dive — Sliema', cat: 'diving',
 departs_from: 'sliema', region: 'central', hub: 'Fond Għadir',
 duration_h: 2, price: 60, max_pax: 4,
 summary: 'First-time scuba in 4 metres of clear water off the Sliema rocks. Pool-like conditions, instructor at your shoulder the whole way.',
 vibe: ['learning','small-group','beginner'],
 operator: 'Maltaqua Dive',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Fond-Ghadir-2560x1440-1.jpeg' },

 { id: 'padi-open-water', name: 'PADI Open Water Course — 4 Days', cat: 'diving',
 departs_from: 'sliema', region: 'central', hub: 'Maltaqua dive centre',
 duration_h: 32, price: 480, max_pax: 4,
 summary: 'Four-day PADI Open Water certification. Theory, confined-water sessions and four open-water dives — typically Cirkewwa Arch + the inland sea.',
 vibe: ['learning','multi-day','beginner'],
 operator: 'Maltaqua Dive',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Ghar-Lapsi-2560x1440-1.jpeg' },

 { id: 'wreck-dive-blenheim', name: 'Wreck Dive — Blenheim Bomber', cat: 'diving',
 departs_from: 'xatt-l-ahmar', region: 'gozo', hub: 'Xatt l-Aħmar, Gozo',
 duration_h: 3, price: 95, max_pax: 6,
 summary: 'Boat dive on a WWII Blenheim bomber at 42m off Xatt l-Aħmar. Advanced + nitrox preferred. Two-tank trip.',
 vibe: ['advanced','technical','small-group','gozo'],
 operator: 'Atlantis Diving Gozo',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Wied-Ghasri-2560x1440-1.jpeg' },

 { id: 'freedive-comino', name: 'Freediving Intro — Comino', cat: 'diving',
 departs_from: 'sliema', region: 'central', hub: 'Sliema Ferries',
 duration_h: 4, price: 110, max_pax: 6,
 summary: 'Half-day intro to freediving in Crystal Lagoon\'s flat clear water. Breath-hold technique, equalisation, depth to 8 metres with a coach on the line.',
 vibe: ['learning','calm','small-group'],
 operator: 'Apnea Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg' },

 { id: 'snorkel-cirkewwa-arch', name: 'Snorkel Tour — Cirkewwa Arch & Tunnel', cat: 'snorkel',
 departs_from: 'cirkewwa', region: 'north', hub: 'Cirkewwa pier',
 duration_h: 2, price: 30, max_pax: 8,
 summary: 'Guided snorkel over the Cirkewwa Arch (sunlit pillars at 6m) and through the rock tunnel. Gear included, no boat needed.',
 vibe: ['small-group','swim','beginner'],
 operator: 'Maltaqua Dive',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Paradise-Bay-2560x14405-1.jpeg' },

 { id: 'snorkel-blue-hole-gozo', name: 'Snorkel Tour — Blue Hole, Gozo', cat: 'snorkel',
 departs_from: 'dwejra', region: 'gozo', hub: 'Dwejra car park',
 duration_h: 2.5, price: 35, max_pax: 6,
 summary: 'The Blue Hole at Dwejra — a 20m-deep natural pool connected to the open sea by a 25m tunnel at 8m depth. Snorkel above, watch the divers below.',
 vibe: ['small-group','swim','gozo'],
 operator: 'Atlantis Diving Gozo',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Wied-Ghasri-2560x1440-1.jpeg' },

 { id: 'pedalboat-mellieha', name: 'Pedalo / Pedal Boat — Mellieħa', cat: 'kayak',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay watersports kiosk',
 duration_h: 1, price: 22, max_pax: 4,
 summary: 'Four-person pedalo with a small slide off the back. Slow, steady, ideal for kids who aren\'t ready for a SUP yet.',
 vibe: ['family','playful','calm','kid-friendly'],
 operator: 'Mellieha Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },

 { id: 'sup-tour-blue-lagoon', name: 'SUP Tour — Around Cominotto', cat: 'kayak',
 departs_from: 'cirkewwa', region: 'north', hub: 'Cirkewwa pier',
 duration_h: 3, price: 60, max_pax: 10,
 summary: 'Paddle from Cirkewwa across to Cominotto and circle it via Crystal Lagoon. 3 hours, guide leads, beginners welcome.',
 vibe: ['small-group','swim','active'],
 operator: 'Maltaqua Sports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Crystal-Lagoon-2560x1440-1.jpeg' },

 { id: 'kayak-marsaxlokk', name: 'Kayak Tour — Marsaxlokk to St Peter\'s Pool', cat: 'kayak',
 departs_from: 'marsaxlokk', region: 'south', hub: 'Marsaxlokk harbour',
 duration_h: 3.5, price: 55, max_pax: 12,
 summary: 'Sea kayak from the colourful luzzu boats of Marsaxlokk around the Delimara point to St Peter\'s Pool. Swim stop, snorkel break, paddle back.',
 vibe: ['small-group','swim','active','south'],
 operator: 'Sea Kayak Malta',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Kalanka-2560x1440-1.jpeg' },

 { id: 'jetski-sunset-mellieha', name: 'Jetski Sunset Run — Mellieħa', cat: 'jetski',
 departs_from: 'mellieha', region: 'north', hub: 'Mellieħa Bay watersports kiosk',
 duration_h: 0.5, price: 75, max_pax: 2,
 summary: '30-minute sunset jetski — solo or tandem, instructor riding alongside. Last departure 30 minutes before sunset.',
 vibe: ['adrenalin','sunset','romantic'],
 operator: 'Mellieha Watersports',
 photo: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg' },
 ];

 window.SUNSPOT_EXPERIENCES = EXP;
 window.SUNSPOT_EXPERIENCE_CATEGORIES = CATEGORIES;
})();
