// ==========================================================
// Sunspot — guide articles (proper content, not just links)
// Each guide is an actual article with body + linked venues.
// Exposed as window.SUNSPOT_GUIDES
// ==========================================================
window.SUNSPOT_GUIDES = [
 {
 slug: 'best-sunsets',
 title: 'Where to watch the sunset in Malta',
 tag: 'Sunset',
 color: '#ff7043',
 readMinutes: 5,
 excerpt: 'A ranked guide to the best sunset spots — pool, rooftop and beach. Where to go, what to order, and what time to arrive.',
 heroEmoji: '',
 heroImage: 'https://cafedelmar.com.mt/wp-content/uploads/2026/01/Cafe-Del-Mar-Wide-Shots-2nd-May-2025-95-scaled.jpg',
 venues: ['cafe-del-mar', 'flo', 'ramla', '1926-la-plage'],
 body: [
 { type: 'p', text: 'Malta sits roughly at the same latitude as Tunis, which means the sun drops fast and the colours go from gold to violet in under 25 minutes. Pick your spot based on that window — and what you want around you.' },
 { type: 'h2', text: '1. Café del Mar Malta · for the iconic version' },
 { type: 'p', text: 'The Ibiza-original sunset house brand transplanted to Qawra. The rooftop infinity pool faces due west, the DJs queue chillout from 17:00, and the cocktail menu peaks at sunset. Book a poolside bed — they sell out by Friday for the weekend.' },
 { type: 'venue', id: 'cafe-del-mar' },
 { type: 'h2', text: '2. FLO Skypool · for the rooftop pool version' },
 { type: 'p', text: 'Nine floors up in Paceville, between Zaha Hadid\'s Mercury Tower and Portomaso. Floating sunbeds inside the heated pool. Tuesday and Saturday are pool-party nights — quieter on the other days.' },
 { type: 'venue', id: 'flo' },
 { type: 'h2', text: '3. Ramla Red · for the wild version' },
 { type: 'p', text: 'Cross to Gozo, drive to Nadur, walk down to the red sand. No DJ, no infinity pool — just Calypso\'s Cave above you and the kind of sunset that doesn\'t need a filter.' },
 { type: 'venue', id: 'ramla' },
 { type: 'h2', text: '4. 1926 La Plage · for the boutique version' },
 { type: 'p', text: 'Art Deco lido on the Sliema seafront. Infinity pool merges into the sea. Stay through to dinner — the "La Vie" evening gastronomy is the move from 18:00.' },
 { type: 'venue', id: '1926-la-plage' },
 { type: 'h2', text: 'Tips' },
 { type: 'ul', items: [
 'Arrive 45 minutes before sunset — get the bed, order the first drink, settle in.',
 'In June/July the sun sets around 20:30; April and September around 19:00.',
 'If the wind is from the west the rooftops are perfect; from the north-east go to the south-facing bays.',
 ]},
 ],
 },
 {
 slug: 'comino-day-trip',
 title: 'Comino Blue Lagoon in 2026: the complete day-trip guide',
 tag: 'Day trip',
 color: '#26c6da',
 readMinutes: 8,
 excerpt: 'New visitor rules in 2026 changed everything. Best times, ferry vs speedboat, where to find shade, what to pack.',
 heroEmoji: '',
 heroImage: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Blue-Lagoon-2560x1440-1.jpeg',
 venues: ['blue-lagoon', 'paradise-bay'],
 body: [
 { type: 'p', text: 'The Blue Lagoon is the single most photographed stretch of water in Malta. From mid-June to August it can hit 2,000 visitors a day on a 200-metre cove — so the 2024 visitor rules added booked entry slots and capped daily numbers. Here\'s the realistic play.' },
 { type: 'h2', text: 'Getting there' },
 { type: 'p', text: 'Two real options: the official Comino Ferry from Ċirkewwa (€15 return, 25 min, runs every 30 min in summer) — or a private speedboat from Sliema (€35–55, 40 min, includes Crystal Lagoon detour). The ferry is fine; the speedboat is what you want if you don\'t love crowds.' },
 { type: 'h2', text: 'When to go' },
 { type: 'p', text: 'Arrive before 9:30am or after 4pm. The middle of the day is brutal — both for crowds and for shade (there is essentially none on the lagoon\'s edge). May–early June and September are the sweet spot: warm water, half the people.' },
 { type: 'h2', text: 'Where to sit' },
 { type: 'p', text: 'If you want a proper sunbed, book through the lagoon-side lounge. Cabanas are limited (six) and VIP tents (two) right on the water — those go a week ahead for weekends.' },
 { type: 'venue', id: 'blue-lagoon' },
 { type: 'h2', text: 'Pair it with' },
 { type: 'p', text: 'Catch the last ferry back, then drive 5 minutes from Ċirkewwa to Paradise Bay for a cooldown swim and a cocktail with no crowds.' },
 { type: 'venue', id: 'paradise-bay' },
 { type: 'h2', text: 'Pack list' },
 { type: 'ul', items: [
 'Reef-safe sunscreen (mandatory under 2026 rules)',
 'Snorkel mask',
 'Refillable water bottle (2L per person)',
 'A wide hat — the only "shade" you can rely on',
 'Cash for the cabin bar (cards work but slow in summer)',
 ]},
 ],
 },
 {
 slug: 'noma-floating',
 title: 'Noma Island: the only floating beach club in Europe',
 tag: 'One-of-a-kind',
 color: '#9c27b0',
 readMinutes: 6,
 excerpt: 'How a day on a 1,750m² floating island actually runs — boat times, what\'s included, is it worth €40+?',
 heroEmoji: '',
 heroImage: 'https://nomaisland.com/wp-content/uploads/2026/02/Untitled-design-1.jpg',
 venues: ['noma'],
 body: [
 { type: 'p', text: 'Noma Island is a 1,750m² floating platform anchored 7 minutes by boat off the Maltese coast. There is nothing else like it in Europe. It opened in 2023; in 2026 it added a sunset session on Friday–Sunday nights. Here\'s what an actual day there looks like.' },
 { type: 'h2', text: 'The boat' },
 { type: 'p', text: 'Pre-booked shuttles leave Sliema Ferries every 30 minutes from 09:30. The crossing is 7 minutes on a flat sea, 12 in a chop. Private water taxi from any other point on the coast is €30 each way — worth it if you\'re bringing a group.' },
 { type: 'h2', text: 'On the island' },
 { type: 'p', text: 'The deck is split into two zones: a sunbed/cabana zone where you can swim off the platform, and a restaurant zone with no swimming (white shirts, set tables). You pick one when you book. Swimming guests get a pool ladder; the depth under the platform is 12m.' },
 { type: 'venue', id: 'noma' },
 { type: 'h2', text: 'Is it worth it?' },
 { type: 'p', text: 'At €40+ for a basic sunbed, yes — if you go in May/June/September. In high August it can get crowded and the shuttle queues. The cabanas (€180) and VIP tents (€380) are worth the upgrade for a special occasion: you get a private corner of a private island.' },
 { type: 'h2', text: 'Watch outs' },
 { type: 'ul', items: [
 'No swimming for restaurant-only guests — pick the right ticket.',
 'The platform moves slightly. If you\'re prone to seasickness, take a tablet before boarding.',
 'Sunset sessions Fri–Sun end at 23:00 — last boat back is 23:30 sharp.',
 ]},
 ],
 },
 {
 slug: 'family-friendly',
 title: 'Family-friendly beach clubs in Malta',
 tag: 'Families',
 color: '#fbc02d',
 readMinutes: 4,
 excerpt: 'Shallow water, kids\' menus, lifeguards, beach wheelchairs — the clubs that actually deliver on the family-friendly promise.',
 heroEmoji: '',
 heroImage: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Mellieha-Bay-2560x1440-1.jpeg',
 venues: ['azure-bay', 'golden-sands', 'hondoq'],
 body: [
 { type: 'p', text: 'Most beach clubs say "family-friendly". Few actually mean it. Here are three that do — based on shallow water, lifeguards, a real kids\' menu, and changing facilities you\'d use yourself.' },
 { type: 'h2', text: 'Mellieħa Bay Club' },
 { type: 'p', text: 'Malta\'s biggest sandy beach. Wide, very shallow — you can walk out 50m before it\'s waist-deep. Heated freshwater pool, beach grill, beach wheelchair on request, free parking.' },
 { type: 'venue', id: 'azure-bay' },
 { type: 'h2', text: 'Golden Sands (Għajn Tuffieħa)' },
 { type: 'p', text: 'The 186-step descent puts off the laziest crowds, which means it\'s never as packed as Mellieħa. Soft sand, dramatic cliffs that throw afternoon shade across the bay. Lifeguards in season.' },
 { type: 'venue', id: 'golden-sands' },
 { type: 'h2', text: 'Ħondoq ir-Rummien (Gozo)' },
 { type: 'p', text: 'A quieter alternative for the Gozo crowd. Mixed sand and pebble, very calm water, views back to Comino. Local kiosk does pastizzi and ice cream — kids approved.' },
 { type: 'venue', id: 'hondoq' },
 ],
 },
 {
 slug: 'pool-parties',
 title: 'The best pool parties in Malta',
 tag: 'Adults only',
 color: '#e91e63',
 readMinutes: 5,
 excerpt: 'FLO Tue & Sat, Café del Mar Thursdays, plus the rotating sunset crew at Manta. Ticket prices, dress codes, DJ residencies.',
 heroEmoji: '',
 heroImage: 'https://floskypool.com/wp-content/uploads/2024/05/about2.jpg',
 venues: ['flo', 'cafe-del-mar', 'manta'],
 body: [
 { type: 'p', text: 'Malta\'s pool-party calendar runs from late May to mid-September. Three venues do it well, on different nights, with different vibes. Here\'s the calendar.' },
 { type: 'h2', text: 'FLO Skypool — Tue & Sat' },
 { type: 'p', text: 'Paceville rooftop, adults only, 28°C heated pool. International DJs on the bookings — tickets from €15 for general entry, sunbeds from €25. Pool party Tuesdays are quieter; Saturdays are full-on.' },
 { type: 'venue', id: 'flo' },
 { type: 'h2', text: 'Café del Mar — Thursday is the night' },
 { type: 'p', text: 'The iconic pool party night. International house DJs from 16:00, runs until 02:00. Sunset is the peak. Dress code kicks in at 19:00 (no flip-flops).' },
 { type: 'venue', id: 'cafe-del-mar' },
 { type: 'h2', text: 'Manta — Saturday brunch carries into the afternoon' },
 { type: 'p', text: 'Not strictly a pool party — but the bottomless brunch from 12 turns into a poolside DJ session from 15:00. Cocktails and Valletta skyline; less wild, more elegant.' },
 { type: 'venue', id: 'manta' },
 ],
 },
 {
 slug: 'gozo-coast',
 title: 'Gozo\'s best beach clubs — a coast itinerary',
 tag: 'Gozo',
 color: '#388e3c',
 readMinutes: 6,
 excerpt: 'Xlendi for seafood, Ramla for red sand, Dwejra for geology, Ħondoq for quiet. A day-by-day coast itinerary.',
 heroEmoji: '',
 heroImage: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/Xlendi-2560x14401-1.jpeg',
 venues: ['xlendi', 'ramla', 'dwejra', 'hondoq'],
 body: [
 { type: 'p', text: 'Gozo is 14km long and you can drive across it in 20 minutes. Which means you can do the entire coast — four very different beach experiences — in a single long weekend. Here\'s how.' },
 { type: 'h2', text: 'Day 1 morning · Xlendi' },
 { type: 'p', text: 'A sheltered, fjord-like inlet on the south coast. Stone steps directly into the water, seafood restaurants on the promenade. The Xlendi Cove Resort includes a 2-course lunch credit at any partner restaurant — use it for lampuki in season.' },
 { type: 'venue', id: 'xlendi' },
 { type: 'h2', text: 'Day 1 afternoon · Dwejra Inland Sea' },
 { type: 'p', text: 'Drive 25 minutes to San Lawrenz. A saltwater lagoon connected to the open sea by a 60-metre cave tunnel. Local boats run €4 tunnel tours. Quieter than the famous spots; you may have the place almost to yourself on a weekday.' },
 { type: 'venue', id: 'dwejra' },
 { type: 'h2', text: 'Day 2 morning · Ramla l-Ħamra' },
 { type: 'p', text: 'The red-sand beach. Park at Nadur, walk down. Calypso\'s Cave (where Odysseus was detained seven years, allegedly) looks down on you. The sand is iron-rich and genuinely red.' },
 { type: 'venue', id: 'ramla' },
 { type: 'h2', text: 'Day 2 afternoon · Ħondoq ir-Rummien' },
 { type: 'p', text: 'Round it off at this quiet south-coast bay looking back to Comino. Local kiosk does drinks and pastizzi. East-facing — so sunrise next morning if you stayed over.' },
 { type: 'venue', id: 'hondoq' },
 ],
 },
 {
 slug: 'natural-pools',
 title: 'The natural pools of Malta',
 tag: 'Natural',
 color: '#5d4037',
 readMinutes: 4,
 excerpt: 'St Peter\'s Pool, Dwejra Inland Sea, Blue Hole. Free entry, sunbed paid. Cliff jumping etiquette, water shoes, access.',
 heroEmoji: '',
 heroImage: 'https://whichbeach.com.mt/wp-content/uploads/2022/01/St.-Peters-Pool-2560x14403-2.jpg',
 venues: ['st-peters', 'dwejra'],
 body: [
 { type: 'p', text: 'Three of Malta\'s best swim spots aren\'t beaches — they\'re natural limestone basins carved by the sea. Entry is free; sunbeds (where available) are paid. Cliff jumping is local tradition. Water shoes are mandatory.' },
 { type: 'h2', text: 'St Peter\'s Pool' },
 { type: 'p', text: 'A kidney-shaped natural pool on the Delimara peninsula. 4m diving platform at the back end. Park at the road, walk 10 minutes over rocks. No sand — flat limestone platforms for sunbathing.' },
 { type: 'venue', id: 'st-peters' },
 { type: 'h2', text: 'Dwejra Inland Sea' },
 { type: 'p', text: 'The most theatrical natural pool — a circular lagoon connected to the open sea by a 60m cave tunnel. Boats motor through the tunnel; you can swim it on a calm day.' },
 { type: 'venue', id: 'dwejra' },
 { type: 'h2', text: 'Cliff jumping rules' },
 { type: 'ul', items: [
 'Always check depth before jumping. The platforms shift after big winter storms.',
 'Don\'t jump alone — and don\'t with kids around the landing zone.',
 'Wear water shoes. The limestone is sharp and the urchins are real.',
 ]},
 ],
 },
 {
 slug: 'brunch-poolside',
 title: 'Where to brunch poolside',
 tag: 'Brunch',
 color: '#f57c00',
 readMinutes: 4,
 excerpt: 'Manta\'s bottomless brunch is the Saturday institution. We also love 1926 La Plage\'s chef-led day menu.',
 heroEmoji: '',
 heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Tas-Sliema._Tign%C3%A9_Seafront_1.jpg/1920px-Tas-Sliema._Tign%C3%A9_Seafront_1.jpg',
 venues: ['manta', '1926-la-plage', 'aqualuna'],
 body: [
 { type: 'p', text: 'Brunch in Malta is a Sliema thing. Three places do it poolside — each with a different angle.' },
 { type: 'h2', text: 'Manta · the bottomless one' },
 { type: 'p', text: 'Saturday 12:00–16:00. Pan-Mediterranean menu plus sushi. Bottomless prosecco, Aperol or Mimosa for €15 supplement. Books a week ahead in season.' },
 { type: 'venue', id: 'manta' },
 { type: 'h2', text: '1926 La Plage · the chef-led one' },
 { type: 'p', text: 'Smaller scale, chef-led, daytime relaxed. Art Deco room, infinity pool. À la carte; the burrata + tomato dish is the order.' },
 { type: 'venue', id: '1926-la-plage' },
 { type: 'h2', text: 'Aqualuna · the view one' },
 { type: 'p', text: 'Across Manoel Island, looking at the Valletta walls glow in late-morning light. Lunch menu is short and good. Less of a "brunch" institution but the setting wins.' },
 { type: 'venue', id: 'aqualuna' },
 ],
 },
 {
 slug: 'date-night',
 title: 'Rooftop date nights',
 tag: 'Date night',
 color: '#5e35b1',
 readMinutes: 5,
 excerpt: 'Twenty Two on the 22nd floor for the view, then walk to Paceville. The 6-hour Malta date itinerary that just works.',
 heroEmoji: '',
 heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Malta_-_St._Julian%27s_-_Portomaso_Marina_02.jpg/1920px-Malta_-_St._Julian%27s_-_Portomaso_Marina_02.jpg',
 venues: ['twentytwo', 'flo'],
 body: [
 { type: 'p', text: 'A 6-hour itinerary for a first or fifth date. Reservations matter — both of these get tight on weekends.' },
 { type: 'h2', text: '18:00 · Twenty Two' },
 { type: 'p', text: '22nd floor of Portomaso Tower — Malta\'s tallest building. Glass walls 360°. Order a Negroni at the sunset hour; the colours change behind the glass for 25 minutes.' },
 { type: 'venue', id: 'twentytwo' },
 { type: 'h2', text: '20:30 · Walk to Spinola Bay' },
 { type: 'p', text: 'Ten minutes downhill. Pick a seafood restaurant on the harbour — Tarragon, Caviar & Bull, or Zafiro. Book ahead.' },
 { type: 'h2', text: '22:00 · FLO Skypool (if it\'s a Tue or Sat)' },
 { type: 'p', text: 'Five minutes from Spinola. The pool stays at 28°C and the music turns up. Stay for the DJ set or just one cocktail by the floating sunbeds.' },
 { type: 'venue', id: 'flo' },
 ],
 },
];
